version: '3'

tasks:
  lint:
    desc: Run linting tools
    cmds:
      - golangci-lint run ./...
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build the binary
    cmds:
      - mkdir -p bin
      - go build -o bin/vt ./cmd/vibetool

  all:
    desc: Run linting, tests, and build
    deps: [lint, test, build]
